package com.team1.trading.api.service;

import com.team1.trading.api.dto.LinkBankAccountRequest;
import com.team1.trading.api.dto.LinkedBankAccountResponse;
import com.team1.trading.api.exception.BankAccountLinkConflictException;
import com.team1.trading.api.exception.BankAccountLinkConflictException.Reason;
import com.team1.trading.api.mapper.BankAccountMapper;
import com.team1.trading.api.mapper.ClientMapper;
import com.team1.trading.api.mapper.UserMapper;
import com.team1.trading.api.mapper.UserMapper.UserRow;
import com.team1.trading.api.security.JwtAuthenticationException;
import com.team1.trading.domain.entity.BankAccount;
import com.team1.trading.domain.entity.Client;
import com.team1.trading.domain.exception.AccountNotFoundException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InOrder;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.willAnswer;
import static org.mockito.BDDMockito.willThrow;
import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class BankAccountLinkServiceTest {

    private static final String USER_ID = "8f14e45f-ceea-4c1b-9d3b-1a2b3c4d5e6f";
    private static final String USERNAME = "priya.menon";
    private static final String EMAIL = "priya.menon@example.com";
    private static final String ACCOUNT_NUMBER = "IN45HDFC0000007890123";
    private static final Long NEW_CLIENT_ID = 42L;

    @Mock
    private UserMapper userMapper;
    @Mock
    private ClientMapper clientMapper;
    @Mock
    private BankAccountMapper bankAccountMapper;

    @InjectMocks
    private BankAccountLinkService service;

    private static LinkBankAccountRequest request() {
        return new LinkBankAccountRequest(ACCOUNT_NUMBER);
    }

    private static BankAccount bankAccount(Long clientId) {
        return new BankAccount(clientId, ACCOUNT_NUMBER,
                new BigDecimal("150000.00"), "HDFC Bank", "HDFC0007890");
    }

    private static UserRow user(Long accountId) {
        UserRow row = new UserRow();
        row.setId(USER_ID);
        row.setUsername(USERNAME);
        row.setEmail(EMAIL);
        row.setAccountId(accountId);
        return row;
    }

    /** clients.client_id is generated by the insert; MyBatis writes it back onto the entity. */
    private void clientInsertGeneratesId() {
        willAnswer(invocation -> {
            Client inserted = invocation.getArgument(0);
            ReflectionTestUtils.setField(inserted, "clientId", NEW_CLIENT_ID);
            return 1;
        }).given(clientMapper).save(any());
    }

    private void anUnlinkedUserAndAnUnclaimedAccount() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        given(bankAccountMapper.findByAccountNumberForUpdate(ACCOUNT_NUMBER)).willReturn(Optional.of(bankAccount(null)));
    }

    @Test
    void claims_an_unclaimed_bank_account_creating_the_client_from_its_holder() {
        anUnlinkedUserAndAnUnclaimedAccount();
        clientInsertGeneratesId();
        given(bankAccountMapper.claim(ACCOUNT_NUMBER, NEW_CLIENT_ID)).willReturn(1);
        given(userMapper.linkAccount(USER_ID, NEW_CLIENT_ID)).willReturn(1);

        LinkedBankAccountResponse response = service.link(USER_ID, request());

        assertThat(response.getAccountId()).isEqualTo(NEW_CLIENT_ID);
        assertThat(response.getAccountNumber()).isEqualTo(ACCOUNT_NUMBER);
        assertThat(response.getBankName()).isEqualTo("HDFC Bank");
        assertThat(response.getIfscCode()).isEqualTo("HDFC0007890");
        assertThat(response.getAccountState()).isEqualTo("ACTIVE");

        // client first, then the claim that names it, then the user's link to it.
        InOrder order = inOrder(clientMapper, bankAccountMapper, userMapper);
        ArgumentCaptor<Client> client = ArgumentCaptor.forClass(Client.class);
        order.verify(clientMapper).save(client.capture());
        order.verify(bankAccountMapper).claim(ACCOUNT_NUMBER, NEW_CLIENT_ID);
        order.verify(userMapper).linkAccount(USER_ID, NEW_CLIENT_ID);
        verify(bankAccountMapper, never()).save(any());

        // bank_account carries no identity of its own (migrations 019, 020): the client is
        // named from the claiming user's username, phone starts null, and the client's email is
        // the user's (unique, their login's), not the bank's.
        assertThat(client.getValue().getName()).isEqualTo(USERNAME);
        assertThat(client.getValue().getPhone()).isNull();
        assertThat(client.getValue().getEmail()).isEqualTo(EMAIL);
        assertThat(client.getValue().getAccountState()).isEqualTo("ACTIVE");
        assertThat(client.getValue().getWalletBalance()).isEqualByComparingTo(BigDecimal.ZERO);
    }

    @Test
    void an_unknown_account_number_is_acc_404_and_writes_nothing() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        given(bankAccountMapper.findByAccountNumberForUpdate(ACCOUNT_NUMBER)).willReturn(Optional.empty());

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(AccountNotFoundException.class);
        verify(clientMapper, never()).save(any());
    }

    @Test
    void an_account_someone_already_claimed_is_acc_409_and_writes_nothing() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        given(bankAccountMapper.findByAccountNumberForUpdate(ACCOUNT_NUMBER)).willReturn(Optional.of(bankAccount(3L)));

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("code", "ACC-409")
                .hasFieldOrPropertyWithValue("reason", Reason.ACCOUNT_ALREADY_CLAIMED);
        verify(clientMapper, never()).save(any());
        verify(bankAccountMapper, never()).claim(anyString(), anyLong());
    }

    @Test
    void refuses_a_user_who_already_has_a_linked_account_without_writing_anything() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(7L)));

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.USER_ALREADY_LINKED);
        verify(bankAccountMapper, never()).findByAccountNumberForUpdate(anyString());
        verify(clientMapper, never()).save(any());
        verify(userMapper, never()).linkAccount(anyString(), anyLong());
    }

    @Test
    void an_email_another_client_holds_is_acc_409() {
        anUnlinkedUserAndAnUnclaimedAccount();
        willThrow(new DuplicateKeyException("clients_email_key")).given(clientMapper).save(any());

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.ALREADY_ON_FILE);
        verify(bankAccountMapper, never()).claim(anyString(), anyLong());
    }

    @Test
    void fails_closed_if_the_guarded_claim_changes_no_row() {
        anUnlinkedUserAndAnUnclaimedAccount();
        clientInsertGeneratesId();
        given(bankAccountMapper.claim(ACCOUNT_NUMBER, NEW_CLIENT_ID)).willReturn(0);

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.ACCOUNT_ALREADY_CLAIMED);
        verify(userMapper, never()).linkAccount(anyString(), anyLong());
    }

    @Test
    void fails_closed_if_the_guarded_user_link_changes_no_row() {
        anUnlinkedUserAndAnUnclaimedAccount();
        clientInsertGeneratesId();
        given(bankAccountMapper.claim(ACCOUNT_NUMBER, NEW_CLIENT_ID)).willReturn(1);
        given(userMapper.linkAccount(USER_ID, NEW_CLIENT_ID)).willReturn(0);

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.USER_ALREADY_LINKED);
    }

    @Test
    void a_token_for_a_user_that_does_not_exist_is_auth_401() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.empty());

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(JwtAuthenticationException.class);
        verify(clientMapper, never()).save(any());
    }
}
