package com.team1.trading.api.service;

import com.team1.trading.api.dto.LinkBankAccountRequest;
import com.team1.trading.api.dto.LinkedBankAccountResponse;
import com.team1.trading.api.exception.BankAccountLinkConflictException;
import com.team1.trading.api.exception.BankAccountLinkConflictException.Reason;
import com.team1.trading.api.mapper.BankAccountMapper;
import com.team1.trading.api.mapper.ClientMapper;
import com.team1.trading.api.mapper.UserMapper;
import com.team1.trading.api.mapper.UserMapper.UserRow;
import com.team1.trading.api.security.JwtAuthenticationException;
import com.team1.trading.domain.entity.BankAccount;
import com.team1.trading.domain.entity.Client;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InOrder;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.willAnswer;
import static org.mockito.BDDMockito.willThrow;
import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class BankAccountLinkServiceTest {

    private static final String USER_ID = "8f14e45f-ceea-4c1b-9d3b-1a2b3c4d5e6f";
    private static final String EMAIL = "priya.menon@example.com";
    private static final Long NEW_CLIENT_ID = 42L;

    @Mock
    private UserMapper userMapper;
    @Mock
    private ClientMapper clientMapper;
    @Mock
    private BankAccountMapper bankAccountMapper;

    @InjectMocks
    private BankAccountLinkService service;

    private static LinkBankAccountRequest request() {
        return new LinkBankAccountRequest("Priya Menon", "+919812345099",
                "IN45HDFC0000009999999", "HDFC Bank", "HDFC0009999");
    }

    /** clients.client_id is generated by the insert; MyBatis writes it back onto the entity. */
    private void clientInsertGeneratesId() {
        willAnswer(invocation -> {
            Client inserted = invocation.getArgument(0);
            ReflectionTestUtils.setField(inserted, "clientId", NEW_CLIENT_ID);
            return 1;
        }).given(clientMapper).save(any());
    }

    private static UserRow user(Long accountId) {
        UserRow row = new UserRow();
        row.setId(USER_ID);
        row.setEmail(EMAIL);
        row.setAccountId(accountId);
        return row;
    }

    @Test
    void links_an_unlinked_user_creating_client_then_bank_account_then_setting_account_id() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        clientInsertGeneratesId();
        given(userMapper.linkAccount(USER_ID, NEW_CLIENT_ID)).willReturn(1);

        LinkedBankAccountResponse response = service.link(USER_ID, request());

        assertThat(response.getAccountId()).isEqualTo(NEW_CLIENT_ID);
        assertThat(response.getAccountNumber()).isEqualTo("IN45HDFC0000009999999");
        assertThat(response.getBankName()).isEqualTo("HDFC Bank");
        assertThat(response.getIfscCode()).isEqualTo("HDFC0009999");
        assertThat(response.getAccountState()).isEqualTo("ACTIVE");

        // clients must go in first: bank_account.client_id is a foreign key to it.
        InOrder order = inOrder(clientMapper, bankAccountMapper, userMapper);
        ArgumentCaptor<Client> client = ArgumentCaptor.forClass(Client.class);
        ArgumentCaptor<BankAccount> bank = ArgumentCaptor.forClass(BankAccount.class);
        order.verify(clientMapper).save(client.capture());
        order.verify(bankAccountMapper).save(bank.capture());
        order.verify(userMapper).linkAccount(USER_ID, NEW_CLIENT_ID);

        assertThat(bank.getValue().getClientId()).isEqualTo(NEW_CLIENT_ID);
        assertThat(bank.getValue().getAccountNumber()).isEqualTo("IN45HDFC0000009999999");
        assertThat(bank.getValue().getEmail()).isEqualTo(EMAIL);
        assertThat(bank.getValue().getName()).isEqualTo("Priya Menon");
        assertThat(bank.getValue().getBalance()).isEqualByComparingTo(BigDecimal.ZERO);

        assertThat(client.getValue().getName()).isEqualTo("Priya Menon");
        // The email comes from the user's record, never from the request.
        assertThat(client.getValue().getEmail()).isEqualTo(EMAIL);
        assertThat(client.getValue().getAccountState()).isEqualTo("ACTIVE");
        assertThat(client.getValue().getWalletBalance()).isEqualByComparingTo(BigDecimal.ZERO);
    }

    @Test
    void refuses_a_user_who_already_has_a_linked_account_without_writing_anything() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(7L)));

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("code", "ACC-409")
                .hasFieldOrPropertyWithValue("reason", Reason.USER_ALREADY_LINKED);

        verify(clientMapper, never()).save(any());
        verify(bankAccountMapper, never()).save(any());
        verify(userMapper, never()).linkAccount(anyString(), anyLong());
    }

    @Test
    void maps_an_account_number_or_email_already_on_file_to_acc_409() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        clientInsertGeneratesId();
        willThrow(new DuplicateKeyException("bank_account_pkey")).given(bankAccountMapper).save(any());

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.ALREADY_ON_FILE);

        verify(userMapper, never()).linkAccount(anyString(), anyLong());
    }

    @Test
    void fails_closed_if_the_guarded_link_update_changes_no_row() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.of(user(null)));
        clientInsertGeneratesId();
        given(userMapper.linkAccount(USER_ID, NEW_CLIENT_ID)).willReturn(0);

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(BankAccountLinkConflictException.class)
                .hasFieldOrPropertyWithValue("reason", Reason.USER_ALREADY_LINKED);
    }

    @Test
    void a_token_for_a_user_that_does_not_exist_is_auth_401() {
        given(userMapper.findForUpdate(USER_ID)).willReturn(Optional.empty());

        assertThatThrownBy(() -> service.link(USER_ID, request()))
                .isInstanceOf(JwtAuthenticationException.class);

        verify(bankAccountMapper, never()).save(any());
    }
}
